In [14]:
from tensorflow.keras.preprocessing.text import one_hot

In [15]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [16]:
# define size of vocab
voc_size = 10000

In [17]:
# one hot representation
one_hot_repr = [one_hot(words,voc_size)for words in sent]

In [18]:
one_hot_repr

[[4021, 1358, 822, 6686],
 [4021, 1358, 822, 6523],
 [4021, 3547, 822, 715],
 [2409, 7288, 1494, 9211, 760],
 [2409, 7288, 1494, 9211, 7841],
 [2858, 4021, 6910, 822, 6566],
 [5317, 8466, 7631, 9211]]

In [19]:
# word embeddings

from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
# from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential


In [20]:
import numpy as np

In [21]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)
# feature representation
dim=10

[[   0    0    0    0 4021 1358  822 6686]
 [   0    0    0    0 4021 1358  822 6523]
 [   0    0    0    0 4021 3547  822  715]
 [   0    0    0 2409 7288 1494 9211  760]
 [   0    0    0 2409 7288 1494 9211 7841]
 [   0    0    0 2858 4021 6910  822 6566]
 [   0    0    0    0 5317 8466 7631 9211]]


In [22]:
model=Sequential()
model.add(Embedding(input_dim=voc_size, output_dim=dim, input_length=sent_length))
model.compile(optimizer='adam', loss='mse')

C:\Users\spnan\anaconda3\Lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [23]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)              │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [24]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 170ms/step


array([[[ 4.18357886e-02,  1.31979026e-02, -3.46369371e-02,
         -3.18212137e-02, -4.07323241e-05, -3.17957401e-02,
          3.20863612e-02,  3.60618494e-02, -9.82464477e-03,
          2.55160592e-02],
        [ 4.18357886e-02,  1.31979026e-02, -3.46369371e-02,
         -3.18212137e-02, -4.07323241e-05, -3.17957401e-02,
          3.20863612e-02,  3.60618494e-02, -9.82464477e-03,
          2.55160592e-02],
        [ 4.18357886e-02,  1.31979026e-02, -3.46369371e-02,
         -3.18212137e-02, -4.07323241e-05, -3.17957401e-02,
          3.20863612e-02,  3.60618494e-02, -9.82464477e-03,
          2.55160592e-02],
        [ 4.18357886e-02,  1.31979026e-02, -3.46369371e-02,
         -3.18212137e-02, -4.07323241e-05, -3.17957401e-02,
          3.20863612e-02,  3.60618494e-02, -9.82464477e-03,
          2.55160592e-02],
        [ 4.66645397e-02, -3.55182998e-02,  2.22038068e-02,
         -4.12581675e-02,  1.93431489e-02,  4.96399663e-02,
         -4.49419729e-02,  2.20968984e-02, -3.983498